language: node_js

cache:
  directories:
    - ~/.npm

node_js:
  - '11'

before_script:
  - npm install -g @vue/cli
  - npm install -g truffle
  - npm install

branches:
  only:
  - master

script:

   - npm run test:unit