language: node_js

cache:
  directories:
    - ~/.npm

node_js:
  - '11'

before_script:
  - npm install -g @vue/cli
  - npm install -g truffle
  - npm install

branches:
  only:
  - master

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
 
after_success:
   - truffle test
   - npm run test:unit